version: '3.9'

services:
  quran-app-dev:
    container_name: quran-memorization-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped
